### ISSUE TITLE
Inspiration?

### ISSUE THREAD

**Issue by pidupuis** [Ajian-studio/GADownloading#2]
Is this work inspired by [Dribbble shot 'Download'](https://dribbble.com/shots/1887815-Download) or [Codrops elastic progress](https://tympanus.net/codrops/2015/09/23/elastic-progress/)?

**Comment by Ajian-studio** [comment]
@pidupuis Yes,  the work is inspired by them. I think this animation is very interesting. What do you think?

**Comment by pidupuis** [comment]
I love it too!
